package cn.advertiser.tencent;

/**
 * @author Michael
 * @date 2024/2/28
 */
public enum RoleType {

    ROLE_TYPE_UNKNOWN,
    ROLE_TYPE_ADMIN,
    ROLE_TYPE_OBSERVER,
    ROLE_TYPE_OPERATOR,
    ROLE_TYPE_TREASURER,
    ROLE_TYPE_ASSISTANT,
    ROLE_TYPE_SELF_OPERATOR,
    ROLE_TYPE_ROOT,
    ROLE_TYPE_AGENCY_BOSS,
    ROLE_TYPE_AGENCY_ADMIN,
    ROLE_TYPE_AGENCY_OBSERVER,
    ROLE_TYPE_AGENCY_TREASURER,
    ROLE_TYPE_AGENCY_OPERATOR,
    ROLE_TYPE_AGENCY_PROVIDER_OPERATOR,
    ROLE_TYPE_AGENCY_PROVIDER_OBSERVER,
    ROLE_TYPE_AGENCY_YYB,
    ROLE_TYPE_AGENCY_AGENT_OPERATOR,
    ROLE_TYPE_AGENCY_SELF_OPERATOR,
    ROLE_TYPE_AGENCY_MDM_BOSS,
    ROLE_TYPE_AGENCY_MDM_ADMIN,
    ROLE_TYPE_AGENCY_MDM_TREASURER,
    ROLE_TYPE_AGENCY_MDM_OBSERVER,
    ROLE_TYPE_AGENCY_MDM_OPERATOR,
    ROLE_TYPE_AGENCY_ORBAC,
    ROLE_TYPE_AGENCY_DESIGNER,
    ROLE_TYPE_SUB_AGENCY_ADMIN;

}
